modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/wendall911/Homeostatic/issues"
license="MIT"

[[mods]]
  modId="homeostatic"
  displayName="Homeostatic"
  description="A mod about body temperature and moisture. Achieving homeostasis after a little trial and error."
  version="${version}"
  displayURL="https://github.com/wendall911/Homeostatic"
  updateJSONURL="https://raw.githubusercontent.com/wendall911/Homeostatic/1.19/files/updates.json"
  authors="wendall911"
  credits="ashar42"
  logoFile="logo.png"
  itemIcon="minecraft:bubble_column"

[[dependencies.homeostatic]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.homeostatic]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.homeostatic]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[17.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.homeostatic]]
    modId="byg"
    mandatory=false
    versionRange="[2.0.1,)"
    ordering="NONE"
    side="BOTH"
